### ISSUE TITLE
Migrate to SFML 2

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/OpenSkyscraper#49]
SFML 2 is stable and usable. In most cases, the API change consists only of a change in naming convention from capitalized camel-case (SetWidth) to the more sensible regular camel-case (setWidth). This should be achievable with a minimal amount of fuzz.

**Comment by fabianschuiki** [comment]
See issue #57 for the current discussion.

**Comment by HoyteKashif** [comment]
Is that issue with branch sfml2_port?

**Comment by fabianschuiki** [comment]
Yes
